# Generated by Django 3.1.4 on 2020-12-22 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlaylistTrack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TrackImg', models.ImageField(blank=True, upload_to='')),
                ('TrackName', models.CharField(max_length=100, verbose_name='Название трека')),
                ('TrackAuthor', models.CharField(max_length=250, verbose_name='Авторы трека')),
                ('TrackTime', models.CharField(max_length=250, verbose_name='Время трека')),
            ],
            options={
                'verbose_name': 'Трек',
                'db_table': 'Треки',
            },
        ),
    ]
