# Generated by Django 3.1.4 on 2020-12-22 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playlisttrack',
            options={'verbose_name': 'Чарт'},
        ),
        migrations.AlterField(
            model_name='playlisttrack',
            name='TrackImg',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Обложка'),
        ),
        migrations.AlterModelTable(
            name='playlisttrack',
            table='Чарт',
        ),
    ]
