# Generated by Django 3.1.4 on 2020-12-22 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0002_auto_20201223_0030'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaylistEgorCrid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TrackImg', models.ImageField(blank=True, upload_to='', verbose_name='Обложка')),
                ('TrackAlbum', models.IntegerField(choices=[[1, '58'], [2, 'Что они знают?'], [3, 'Холостяк']])),
                ('TrackName', models.CharField(max_length=100, verbose_name='Название трека')),
                ('TrackAuthor', models.CharField(max_length=250, verbose_name='Авторы трека')),
                ('TrackTime', models.CharField(max_length=250, verbose_name='Время трека')),
            ],
            options={
                'verbose_name': 'Егор Крид',
                'db_table': 'Егор Крид',
            },
        ),
    ]
