# Generated by Django 3.1.4 on 2020-12-22 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0003_playlistegorcrid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playlistegorcrid',
            options={'verbose_name': 'Трэк', 'verbose_name_plural': 'Егор Крид'},
        ),
        migrations.AlterModelOptions(
            name='playlisttrack',
            options={'verbose_name': 'Трэк', 'verbose_name_plural': 'Чарт'},
        ),
        migrations.AlterField(
            model_name='playlistegorcrid',
            name='TrackAlbum',
            field=models.IntegerField(choices=[[1, '58'], [2, 'Что они знают?'], [3, 'Холостяк']], verbose_name='Альбом'),
        ),
        migrations.AlterField(
            model_name='playlistegorcrid',
            name='TrackAuthor',
            field=models.CharField(default='Егор Крид', max_length=250, verbose_name='Авторы трека'),
        ),
    ]
